<?php

namespace Blog\Models;

use Blog\Services\FullTextSearch;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * @property string                                   $title      title
 * @property string                                   $slug       slug
 * @property \Carbon\Carbon                           $created_at created at
 * @property \Carbon\Carbon                           $updated_at updated at
 * @property \Illuminate\Database\Eloquent\Collection $post       hasMany
 */
class Category extends Model
{
    use FullTextSearch;

    /**
     * Database table name
     */
    protected $table = 'blog_categories';
    /**
     * Protected columns from mass assignment
     */
    protected $fillable = ['parent_id', 'title', 'slug'];

    protected $searchable = ['title'];

    /**
     * Date time columns.
     */
    protected $dates = [];

    public static function boot()
    {
        static::creating(function ($model) {
            if (empty($model->slug)) {
                $model->slug = Str::slug($model->title);
            }
            return true;
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * posts
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function posts()
    {
        return $this->hasMany(Post::class, 'category_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children()
    {
        return $this->hasMany(static::class, 'parent_id');
    }

    public function parentCategory()
    {
        return $this->belongsTo(static::class, 'parent_id');
    }

    public function scopeParent($query)
    {
        return $query->whereNull('parent_id');
    }

    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

}
